# Generated by Django 3.2.8 on 2021-10-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_userprofile_wishlists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='wishlists',
        ),
    ]
