# Generated by Django 3.2.8 on 2021-10-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='clothing_material',
            field=models.CharField(blank=True, choices=[('100% cotton', '100% cotton'), ('50/50 cotton/polyester', '50/50 cotton/polyester')], max_length=256, null=True),
        ),
    ]
