# Generated by Django 3.2.8 on 2021-10-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_default_full_name'),
        ('products', '0004_alter_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='users_wishlist',
            field=models.ManyToManyField(blank=True, related_name='user_wishlist', to='profiles.UserProfile'),
        ),
    ]
