# Generated by Django 3.2.8 on 2021-10-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_review_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='clothing_material',
            field=models.CharField(blank=True, choices=[('100% cotton', '100% cotton'), ('50/50', '50/50')], max_length=256, null=True),
        ),
    ]
